[package]
name = "project_euler"
version = "0.1.0"
authors = ["Olivier Chass√© St-Laurent <oliviercsl@gmail.com>"]
edition = "2018"

[dependencies]
counter = "0.4"
chrono = "0.4"
itertools = "0.8"
num = "0.2.0"
permutohedron = "0.2"
primal = "0.2.3"
rand = "0.7.2"
